Repository team-peekabook/Peekabook-AOS, pull requests merged in 2023-05, with the labels that each got.

#194 #193 [fix] UiEvent로 서버 중복 요청 방지
  app/src/main/java/com/sopt/peekabookaos/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeScannerFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createBook/CreateBookFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createBook/CreateBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/editBook/EditBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/editBook/EditBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/user/SearchUserActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/user/SearchUserViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/withdraw/WithdrawActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/withdraw/WithdrawViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/util/UiState.kt
  app/src/main/res/layout/activity_search_user.xml
  app/src/main/res/layout/activity_withdraw.xml
  app/src/main/res/layout/fragment_create_book.xml
  app/src/main/res/layout/fragment_search_book.xml
Labels: fix, Pull Request🔥, 영주🐼

#196 #195 [fix] 사용자 차단리스트 수정
  app/src/main/res/layout/activity_blocked_user.xml
  app/src/main/res/values/strings.xml
Labels: fix, Pull Request🔥, 하정🐥

#198 #197 [ chore] 회원 정보 입력, 팔로우 시 뜨는 알림 item 제약 수정
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/values/strings.xml
Labels: chore, Pull Request🔥, 강희🐬

#200 #199 [chore] qa수정(문의하기 링크연결, editText밑줄 제거)
  app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
  app/src/main/res/values/strings.xml
Labels: chore, Pull Request🔥, 하정🐥

#203 #201 [feat] 난독화
  .github/workflows/pr_checker.yml
  app/build.gradle
  app/proguard-glide.pro
  app/proguard-okhttp3.pro
  app/proguard-retrofit2.pro
  app/proguard-rules.pro
  app/src/debug/ic_launcher-playstore.png
Labels: feat, Pull Request🔥, 영주🐼

#207 #205 [fix] 알림 empty뷰, 책장 pick 버튼 비활성화
  app/src/main/res/drawable/shape_gray_fill_0_rect.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/fragment_bookshelf.xml
  app/src/main/res/values/strings.xml
Labels: fix, Pull Request🔥, ui, 강희🐬

#211 #210 [QA] 책등록에서 책상세보기로 LOCATION 보내기, 책삭제 팝업 간격 조정
  app/src/main/java/com/sopt/peekabookaos/presentation/createBook/CreateBookFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/res/layout/dialog_warning.xml
Labels: Pull Request🔥, 영주🐼, QA

#213 #208 [fix] 유저 프로필 null처리
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/SearchUserResponse.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/User.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/ic_profile_default.xml
Labels: fix, Pull Request🔥, 영주🐼

#215 #214 [QA] userInput 프로필 터치 영역 확대 / bookshelf 친구 empty view 위치 조정
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
  app/src/main/res/layout/fragment_bookshelf.xml
Labels: Pull Request🔥, ui, 강희🐬, QA
