Repository team-peekabook/Peekabook-AOS, pull requests merged in 2023-04, with the labels that each got.

#145 #144 [ui] Bookshelf empty 뷰 작업
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
  app/src/main/res/drawable/ic_bookshelf_bottom_empty_friend.xml
  app/src/main/res/layout/fragment_bookshelf.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 강희🐬

#158 #147 [ui] 탈퇴하기 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/local/LocalPrefDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/ClearLocalPrefUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/withdraw/WithdrawActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/withdraw/WithdrawDialog.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/withdraw/WithdrawViewModel.kt
  app/src/main/res/drawable/ic_withdraw_delete.xml
  app/src/main/res/layout/activity_withdraw.xml
  app/src/main/res/layout/dialog_withdraw.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 영주🐼

#162 #160 [feat] 인터넷 에러 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/networkError/NetworkErrorActivity.kt
  app/src/main/java/com/sopt/peekabookaos/util/extensions/ContextExt.kt
  app/src/main/res/layout/activity_network_error.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request🔥, 영주🐼

#161 #149 [ui] 차단사용자 관리뷰
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/block/FriendBlockAdapter.kt
  app/src/main/res/layout/activity_block.xml
  app/src/main/res/layout/item_block.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 하정🐥

#148 #141 [ui] 신고하기뷰/뷰작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportConfirmDialog.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportViewModel.kt
  app/src/main/res/layout/activity_report.xml
  app/src/main/res/layout/dialog_report_confirm.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 하정🐥

#166 #164 [feat] 리프래쉬 api 구현
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/LoginResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/RefreshResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/RefreshRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/RefreshService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/RefreshDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/di/RefreshRetrofitModule.kt
  app/src/main/java/com/sopt/peekabookaos/di/RepositoryModule.kt
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Token.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/RefreshRepository.kt
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request🔥, 영주🐼

#170 #154 [ui/feat] 사용자 검색 뷰에 차단해제 구현
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/SearchUserResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/BlockRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/BlockService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/BlockDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/di/RepositoryModule.kt
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/User.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/BlockRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/DeleteBlockUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/user/SearchUserViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/shape_g2_line_circle.xml
  app/src/main/res/layout/activity_search_user.xml
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request🔥, ui, 영주🐼

#169 #159 [fix] 마이페이지 수정
  app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: fix, Pull Request🔥, 하정🐥

#172 #171 [feat] 탈퇴하기 api 구현
  app/src/main/java/com/sopt/peekabookaos/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/AuthService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/AuthDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/DeleteUserUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/withdraw/WithdrawViewModel.kt
Labels: feat, Pull Request🔥, 영주🐼

#167 #163 [feat] 회원정보 입력 뷰 api(회원가입/닉네임 중복)
  app/src/main/java/com/sopt/peekabookaos/data/entity/request/DuplicateRequest.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/DuplicateResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/UserInputRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/UserInputService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/UserInputDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/di/RepositoryModule.kt
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/UserInputRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PatchSignUpUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PostDuplicateUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/util/ContentUriRequestBody.kt
Labels: feat, Pull Request🔥, 강희🐬

#176 #168 [feat] bookshelf 서버- 차단, 언팔로우 api
  app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/ShelfService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/ShelfDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/ShelfRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PostBlockUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputViewModel.kt
Labels: feat, Pull Request🔥, 강희🐬

#184 #175 [feat] 신고하기뷰 서버
  app/src/main/java/com/sopt/peekabookaos/data/entity/request/ReportRequest.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/ReportRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/ReportService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/ReportDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/di/RepositoryModule.kt
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/ReportRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PostReportUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportDialog.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportViewModel.kt
  app/src/main/res/layout/activity_report.xml
  app/src/main/res/layout/dialog_report.xml
Labels: feat, Pull Request🔥, 하정🐥

#183 #165 [feat] 차단하기뷰/다이얼로그 연결&서버
  app/src/main/java/com/sopt/peekabookaos/data/entity/FriendProfileEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/ProfileEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/FriendShelfResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/MyShelfResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/BlockRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/BlockService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/BlockDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/FriendList.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/FriendShelf.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/MyShelf.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/SelfIntro.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/User.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/BlockRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/GetBlockUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/block/FriendBlockAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/block/UnblockDialog.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfFriendAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommedationViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookViewModel.kt
  app/src/main/res/layout/dialog_unblock.xml
  app/src/main/res/layout/item_block.xml
  app/src/main/res/layout/item_bookshelf_user_profile.xml
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request🔥, ui, 하정🐥

#187 #178 [feat] 마이페이지 서버
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/data/entity/ProfileEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/FriendShelfResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/MyShelfResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/MyPageRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/MyPageService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/MyPageDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/di/RepositoryModule.kt
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/MyPageRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/GetMyPageUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockedUserActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockedUserAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockedUserViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/block/UnblockDialog.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageViewModel.kt
  app/src/main/res/layout/activity_blocked_user.xml
  app/src/main/res/layout/dialog_unblock.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request🔥, 하정🐥
