Repository team-peekabook/Peekabook-AOS, pull requests merged in 2023-03, with the labels that each got.

#121 #119 [refactor] 추천보기뷰 서버 도메인으로 변경
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/RecommendEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/RecommendResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/RecommendRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Recommend.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/RecommendBookList.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/RecommendRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/GetRecommendUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PostRecommendationUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommend/BookRecommendAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendViewModel.kt
  app/src/main/res/layout/item_recommend.xml
Labels: Pull Request🔥, refactor, 하정🐥

#122 #120 [refactor] bookshelf/notification domain 변경
  app/src/main/java/com/sopt/peekabookaos/data/entity/BookEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/BooksEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/FollowId.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/FriendList.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/FriendListEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/Notification.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/NotificationEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/PickModify.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/Picks.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/PicksEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/SelfIntroEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/DetailResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/FriendShelfResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/MyShelfResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/NotificationRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/NotificationRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/NotificationService.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/ShelfService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/NotificationDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/ShelfDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/di/RepositoryModule.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Books.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Detail.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/FriendList.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/FriendShelf.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/MyShelf.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Notification.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Picks.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/SelfIntro.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/NotificationRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/ShelfRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/GetFriendShelfUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/GetMyShelfUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/GetPickUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PatchPickUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfFriendAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfPickAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfShelfAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommedationViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookViewModel.kt
  app/src/main/res/layout/item_bookshelf_pick.xml
  app/src/main/res/layout/item_bookshelf_shelf.xml
  app/src/main/res/layout/item_bookshelf_user_profile.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/layout/item_pick_modify.xml
Labels: Pull Request🔥, refactor, 강희🐬

#128 #116 [refactor] 책 등록하기/수정하기 뷰 프래그먼트와 액티비티로 각각 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/data/entity/request/EditBookRequest.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/CreateBookResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/BookRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/CreateUpdateRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/BookService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/BookDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/CreateUpdateDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/di/RepositoryModule.kt
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/BookRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PatchBookUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PatchEditBookUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PostCreateBookUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeScannerFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/book/BookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createBook/CreateBookFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createBook/CreateBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/editBook/EditBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/editBook/EditBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/updateBook/UpdateBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/updateBook/UpdateBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/util/extensions/UiEvent.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_edit_book.xml
  app/src/main/res/layout/fragment_create_book.xml
  app/src/main/res/navigation/nav_book.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, refactor, 영주🐼

#132 #130 [refactor] PickModify patchPick parameter / onSuccess
  app/src/main/java/com/sopt/peekabookaos/data/entity/SelfIntroEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/ShelfDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/ShelfRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PatchPickUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
Labels: Pull Request🔥, refactor, 강희🐬

#127 #126 [refactor] 추천보기뷰 request 파라미터 변경
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/RecommendationResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/RecommendRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/RecommendDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Detail.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/RecommendRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PostRecommendationUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommedationViewModel.kt
Labels: Pull Request🔥, refactor, 하정🐥

#133 #129 [refactor] 상세뷰 수정
  app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/DetailRepository.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
Labels: Pull Request🔥, refactor, 하정🐥

#139 #123 [refactor] 책추천하기뷰 액티비티를 프래그먼트로 변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/data/entity/RecommendEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/request/RecommendationRequest.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/RecommendResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/RecommendRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/RecommendDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/RecommendRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PostRecommendationUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommedationViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationFragment.kt
  app/src/main/res/layout/activity_recommendation.xml
  app/src/main/res/layout/fragment_recommendation.xml
Labels: Pull Request🔥, refactor, 하정🐥

#137 #134 [feat] 카카오 로그인 구현
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/PeekabookApplication.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/KakaoLoginService.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfFriendAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfPickAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfShelfAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createBook/CreateBookFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createBook/CreateBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/editBook/EditBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/editBook/EditBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/login/LoginActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/login/LoginViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/main/MainActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommend/BookRecommendAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/user/SearchUserActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/user/SearchUserViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
  app/src/main/java/com/sopt/peekabookaos/util/ItemDiffCallback.kt
  app/src/main/java/com/sopt/peekabookaos/util/KakaoLoginCallback.kt
  app/src/main/java/com/sopt/peekabookaos/util/KeyBoardUtil.kt
  app/src/main/java/com/sopt/peekabookaos/util/OnSingleClickListener.kt
  app/src/main/java/com/sopt/peekabookaos/util/ToastMessageUtil.kt
  app/src/main/java/com/sopt/peekabookaos/util/UiEvent.kt
  app/src/main/java/com/sopt/peekabookaos/util/UiState.kt
  app/src/main/java/com/sopt/peekabookaos/util/extensions/ContextExt.kt
  app/src/main/res/drawable/shape_yellow_fill_8_rect.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  settings.gradle
Labels: feat, Pull Request🔥, 영주🐼

#153 #138 [feat] 로그인 api 및 토큰 로컬에 저장하는 로직 구현
  app/src/main/java/com/sopt/peekabookaos/data/entity/request/LoginRequest.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/LoginResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/AuthService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/local/LocalPrefDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/AuthDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/di/RepositoryModule.kt
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitServiceModule.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Login.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/InitTokenUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PostLoginUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/socialLogin/SocialLoginFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/socialLogin/SocialLoginViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/util/KakaoLoginCallback.kt
Labels: feat, Pull Request🔥, 영주🐼

#156 #155 [chore] drawable 정리
  app/src/main/res/drawable-xxxhdpi/img.png
  app/src/main/res/drawable/background_splash.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_peeka_close.xml
  app/src/main/res/drawable/ic_search_plus.xml
  app/src/main/res/drawable/shape_red_line.xml
  app/src/main/res/drawable/shape_red_line_circle.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_edit_book.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/activity_pick_modify.xml
  app/src/main/res/layout/activity_search_user.xml
  app/src/main/res/layout/dialog_barcode_error.xml
  app/src/main/res/layout/fragment_barcode_scanner.xml
  app/src/main/res/layout/fragment_bookshelf.xml
  app/src/main/res/layout/fragment_create_book.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_recommendation.xml
  app/src/main/res/layout/fragment_search_book.xml
  app/src/main/res/layout/item_bookshelf_user_profile.xml
  app/src/main/res/layout/item_search_book.xml
Labels: chore, Pull Request🔥, 영주🐼
