Repository team-peekabook/Peekabook-AOS, pull requests merged in 2023-09, with the labels that each got.

#256 #255 [QA] 신고하기 글자수 제한
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
  app/src/main/res/drawable/shape_white66fill_redline_0_rect.xml
  app/src/main/res/drawable/shape_white88fill_redline_0_rect.xml
  app/src/main/res/layout/activity_report.xml
  app/src/main/res/layout/fragment_user_input.xml
Labels: Pull Request🔥, 영주🐼, 하정🐥, 강희🐬, QA

#259 #257 [hotfix] RecommendEntity의friendImage nullable 처리
  app/src/main/java/com/sopt/peekabookaos/data/entity/RecommendEntity.kt
Labels: hotfix🚨, Pull Request🔥, 하정🐥

#261 #260 [ui] tv_notification_book_title margin 수정(mention과 동일 margin)
  app/src/main/res/layout/item_notification.xml
Labels: Pull Request🔥, ui, 강희🐬

#264 #263 [fix] 28이하 기기에서 프로필 수정뷰 진입 막는 분리처리
  app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
  app/src/main/res/values/strings.xml
Labels: fix, Pull Request🔥, 하정🐥

#267 #266 [chore] 파이어베이스 gradle 추가 및 yml 수정
  .github/workflows/pr_checker.yml
  app/build.gradle
  build.gradle
Labels: chore, Pull Request🔥, 영주🐼
