Repository team-peekabook/Peekabook-AOS, pull requests merged in 2023-06, with the labels that each got.

#219 #216 [qa] bookshelf bottomsheet 높이 조정
  app/src/main/res/values-hdpi/dimen.xml
  app/src/main/res/values-mdpi/dimen.xml
  app/src/main/res/values-xhdpi/dimen.xml
  app/src/main/res/values-xxhdpi/dimen.xml
  app/src/main/res/values-xxxhdpi/dimen.xml
Labels: Pull Request🔥, ui, 강희🐬, QA

#221 #220 [QA] 책상세뷰 스크롤뷰 추가
  app/src/main/res/layout/activity_detail.xml
Labels: 하정🐥, QA

#223 #222 [QA] 리프래시 api 400일 때 자동로그인 해제 로직 구현
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
Labels: Pull Request🔥, 영주🐼, QA

#226 #225 [QA] 책검색뷰 작가명 제약 수정
  app/src/main/res/layout/item_search_book.xml
Labels: Pull Request🔥, 영주🐼, QA

#224 #218 [QA] 프로필 이미지 엔티티 null처리 및 도메인 엔티티 정리
  app/src/main/java/com/sopt/peekabookaos/data/entity/FriendProfileEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/NotificationEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/PicksEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/ProfileEntity.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/DetailResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/FriendShelfResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/MyShelfResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/BookDetail.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Detail.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/FriendShelf.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Notification.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Onboarding.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Recommend.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/RecommendBookList.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Recommendation.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Shelf.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/DetailRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/ShelfRepository.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/editBook/EditBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/editBook/EditBookViewModel.kt
Labels: Pull Request🔥, 영주🐼, QA

#229 #206 [fix] user input 기본이미지 null 처리
  app/src/main/java/com/sopt/peekabookaos/data/repository/UserInputRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/UserInputService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/UserInputDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/UserInputRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PatchSignUpUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputViewModel.kt
Labels: fix, Pull Request🔥, ui, 강희🐬

#231 #230 [qa] user input 정규식 수정
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputViewModel.kt
Labels: Pull Request🔥, 강희🐬, QA

#192 #151 [ui&feat] 프로필수정 ui, 서버
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/ProfileModifyResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/MyPageRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/MyPageService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/MyPageDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/MyPageRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PatchProfileModifyUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyBottomSheetFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/util/ImageUtil.kt
  app/src/main/res/drawable/ic_check_inactive.xml
  app/src/main/res/drawable/ic_my_page_edit.xml
  app/src/main/res/layout/activity_profile_modify.xml
  app/src/main/res/layout/dialog_profile_modify_botton_sheet.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: feat, Pull Request🔥, ui, 하정🐥

#233 #232 [QA] 정규표현식 수정, 중복확인 체크메세지 로직 수정
  app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputViewModel.kt
Labels: Pull Request🔥, 하정🐥, QA
