Repository team-peekabook/Peekabook-AOS, pull requests merged in 2023-02, with the labels that each got.

#109 #108 [refact] Book 네비게이션 설정, 도메인 분리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/SearchUserResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/SearchRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/di/RepositoryModule.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/User.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/SearchRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/DeleteFollowUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/GetSearchUserUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/PostFollowUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeScannerActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeScannerFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/book/BookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createBook/CreateBookFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/user/SearchUserViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/updateBook/UpdateBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/updateBook/UpdateBookViewModel.kt
  app/src/main/res/layout/activity_book.xml
  app/src/main/res/layout/fragment_barcode_scanner.xml
  app/src/main/res/layout/fragment_recommendation.xml
  app/src/main/res/layout/fragment_search_book.xml
  app/src/main/res/layout/layout_create_update_book.xml
  app/src/main/res/navigation/nav_book.xml
Labels: Pull Request🔥, refactor, 영주🐼

#110 #106 [refactor] bookshelf 기기 대응 및 xml 수정
  app/src/main/java/com/sopt/peekabookaos/data/entity/Picks.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfShelfDecoration.kt
  app/src/main/res/layout/fragment_bookshelf.xml
  app/src/main/res/layout/item_bookshelf_pick.xml
  app/src/main/res/layout/item_bookshelf_user_profile.xml
  app/src/main/res/values-hdpi/dimen.xml
  app/src/main/res/values-mdpi/dimen.xml
  app/src/main/res/values-xhdpi/dimen.xml
  app/src/main/res/values-xxhdpi/dimen.xml
  app/src/main/res/values-xxxhdpi/dimen.xml
Labels: Pull Request🔥, refactor, 강희🐬

#115 #112 [refactor] 바코드 검색, 텍스트 검색 액티비티에서 프래그먼트로 변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/User.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeErrorDialog.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeScannerActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeScannerFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/book/BookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createBook/CreateBookFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/user/SearchUserViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/updateBook/UpdateBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/util/extensions/BundleExt.kt
  app/src/main/res/animator/anim_from_bottom.xml
  app/src/main/res/animator/anim_from_left.xml
  app/src/main/res/animator/anim_from_right.xml
  app/src/main/res/animator/anim_from_top.xml
  app/src/main/res/animator/anim_to_bottom.xml
  app/src/main/res/animator/anim_to_left.xml
  app/src/main/res/animator/anim_to_right.xml
  app/src/main/res/animator/anim_to_top.xml
  app/src/main/res/drawable/ic_barcode_line.xml
  app/src/main/res/layout/activity_barcode_scanner.xml
  app/src/main/res/layout/activity_book.xml
  app/src/main/res/layout/activity_search_book.xml
  app/src/main/res/layout/fragment_barcode_scanner.xml
  app/src/main/res/layout/fragment_search_book.xml
  app/src/main/res/navigation/nav_book.xml
  build.gradle
Labels: Pull Request🔥, refactor, 영주🐼

#111 #107 [refactor] 서버 도메인으로 변경
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/DetailResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/di/RepositoryModule.kt
  app/src/main/java/com/sopt/peekabookaos/domain/entity/Detail.kt
  app/src/main/java/com/sopt/peekabookaos/domain/repository/DetailRepository.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/DeleteDetailUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/domain/usecase/GetDetailUseCase.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
Labels: Pull Request🔥, refactor, 하정🐥

#117 #114 [fix] 알람 xml 수정
  app/src/main/res/layout/item_notification.xml
Labels: fix, Pull Request🔥, 강희🐬
