Repository team-peekabook/Peekabook-AOS, pull requests merged in 2023-07, with the labels that each got.

#237 [QA] 회원가입뷰 프로필 수정뷰 닉네임 길이 제한 수정
  app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputViewModel.kt
Labels: Pull Request🔥, 하정🐥, QA

#239 [QA] #238 프로필 수정뷰 추가버튼 위치 수정, 신고하기뷰 뒤로가기 버튼 클릭가능 여부 수정
  app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportActivity.kt
  app/src/main/res/layout/activity_profile_modify.xml
Labels: fix, Pull Request🔥, 하정🐥, QA

#244 #243 [feat] 바코드 검색뷰 안내메세지 중앙정렬
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeGuideView.kt
Labels: Pull Request🔥, 영주🐼, QA
