Repository team-peekabook/Peekabook-AOS, pull requests merged in 2023-10, with the labels that each got.

#268 #265 [fix] 회원정보입력/프로필수정 camera bottomsheet 제거
  .idea/kotlinc.xml
  app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyBottomSheetFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputBottomSheetFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
  app/src/main/res/layout/dialog_profile_bottom_sheet.xml
Labels: fix, Pull Request🔥, 강희🐬

#270 #269 [ui] 책상세보기뷰 메모 visible 처리
  app/src/main/res/layout/activity_detail.xml
Labels: Pull Request🔥, ui, 영주🐼

#272 #271 [chore] 앱 이름 수정
  app/src/main/res/values/strings.xml
Labels: chore, Pull Request🔥, 영주🐼
