Repository team-peekabook/Peekabook-AOS, pull requests merged in 2023-01, with the labels that each got.

#8 #5 [ui] 책 등록하기 / RegisterBook 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/data/entity/BookRegister.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/registerBook/RegisterBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/registerBook/RegisterBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/util/extensions/ContextExt.kt
  app/src/main/res/drawable/ic_register_book_close.xml
  app/src/main/res/drawable/ic_register_book_save.xml
  app/src/main/res/drawable/shape_whitefill_redline_0_rect.xml
  app/src/main/res/layout/activity_register_book.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 영주🐼

#9 #7 [ui] 책장 / 책장 뷰 구현
  app/build.gradle
  app/src/main/java/com/sopt/peekabookaos/data/entity/bookshelf/FriendProfileData.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/bookshelf/PickData.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/bookshelf/ShelfData.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/bookshelf/UserData.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfFriendAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfPickAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfShelfAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfShelfDecoration.kt
  app/src/main/java/com/sopt/peekabookaos/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/ic_bookshelf_add_book.xml
  app/src/main/res/drawable/ic_bookshelf_friend_plus.xml
  app/src/main/res/drawable/ic_bookshelf_logo.xml
  app/src/main/res/drawable/ic_bookshelf_more.xml
  app/src/main/res/drawable/ic_bookshelf_notification.xml
  app/src/main/res/drawable/shape_light_beige_fill_top15_rect.xml
  app/src/main/res/drawable/shape_red_line_0_circle.xml
  app/src/main/res/drawable/shape_red_line_0_rect.xml
  app/src/main/res/drawable/shape_white_redlines_0_rect.xml
  app/src/main/res/layout/fragment_bookshelf.xml
  app/src/main/res/layout/item_bookshelf_friend_profile.xml
  app/src/main/res/layout/item_bookshelf_pick.xml
  app/src/main/res/layout/item_bookshelf_shelf.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: Pull Request🔥, ui, 강희🐬

#12 #11 [ui] 책 수정하기 / CreateUpdateBook 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/data/entity/Book.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/BookRegister.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/FriendProfile.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/Pick.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/Shelf.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/User.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/bookshelf/FriendProfileData.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/bookshelf/ShelfData.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfFriendAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfPickAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfShelfAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createUpdateBook/CreateUpdateBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createUpdateBook/CreateUpdateBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/registerBook/RegisterBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/registerBook/RegisterBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/util/extensions/IntentExt.kt
  app/src/main/res/drawable/ic_create_update_book_close.xml
  app/src/main/res/drawable/ic_create_update_book_save.xml
  app/src/main/res/layout/activity_create_update_book.xml
  app/src/main/res/layout/activity_register_book.xml
  app/src/main/res/layout/item_bookshelf_friend_profile.xml
  app/src/main/res/layout/item_bookshelf_pick.xml
  app/src/main/res/layout/item_bookshelf_shelf.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 영주🐼

#18 #17 [ui] 마이페이지 / MyPage 뷰 구현
  app/src/main/res/drawable/ic_peekabook_logo.xml
  app/src/main/res/layout/fragment_bookshelf.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 영주🐼

#15 #6 [ui] 추천받은 책/추천받은 책 뷰 구현
  app/src/main/java/com/sopt/peekabookaos/data/entity/Recommend.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommend/BookRecommendAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendFragment.kt
  app/src/main/res/drawable/selector_recommend_textview.xml
  app/src/main/res/drawable/shape_whitefill_redline_0_rect.xml
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/layout/item_recommend.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 하정🐥

#22 #19 [ui] 책 상세뷰 / 책 상세뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
  app/src/main/res/drawable/shape_red_line_0_rect.xml
  app/src/main/res/drawable/shape_white88fill_redline_0_rect.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_bookshelf.xml
  app/src/main/res/layout/item_bookshelf_pick.xml
  app/src/main/res/values/strings.xml
Labels: ui, 하정🐥

#32 #16 [ui] 책장 / 책장 뷰 구현
  app/build.gradle
  app/src/main/java/com/sopt/peekabookaos/data/entity/FriendProfile.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/FriendUser.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/Pick.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfFriendAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfShelfDecoration.kt
  app/src/main/res/drawable/ic_bookshlef_indicator.xml
  app/src/main/res/drawable/shape_white30fill_redlines_0_rect.xml
  app/src/main/res/layout/fragment_bookshelf.xml
  app/src/main/res/layout/item_bookshelf_pick.xml
  app/src/main/res/layout/item_bookshelf_shelf.xml
  app/src/main/res/layout/item_bookshelf_user_profile.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 강희🐬

#33 #27 [ui] 책 검색(텍스트) / SearchBookActivity 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeScannerActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/SearchBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/SearchBookAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/SearchBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/util/extensions/KeyBoardUtil.kt
  app/src/main/res/drawable/ic_item_search_small_plus.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_error.xml
  app/src/main/res/layout/activity_search_book.xml
  app/src/main/res/layout/item_search_book.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 영주🐼

#23 #21 [ui] 추천뷰/ 추천뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/data/entity/FriendUser.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommedationViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationActivity.kt
  app/src/main/res/drawable/ic_peeka_check.xml
  app/src/main/res/layout/activity_recommendation.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 하정🐥

#34 #20 [ui] pick뷰 / pick view 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/data/entity/PickModify.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/Shelf.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfFriendAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyDecoration.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
  app/src/main/res/drawable/ic_create_update_book_save.xml
  app/src/main/res/drawable/shape_red_fill_circle.xml
  app/src/main/res/layout/activity_create_update_book.xml
  app/src/main/res/layout/activity_pick_modify.xml
  app/src/main/res/layout/item_bookshelf_shelf.xml
  app/src/main/res/layout/item_pick_modify.xml
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 강희🐬

#37 #29 [fix] 전체뷰/ 메모리릭 방지 위한 adapter 수정
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendFragment.kt
Labels: fix, 하정🐥

#39 #35 [ui] 알림 / 알림 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/data/entity/Notification.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfPickAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfShelfAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
  app/src/main/res/drawable/ic_notification_close.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/activity_pick_modify.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 강희🐬

#41 #30 [ui] 책검색(바코드) / 에러다이얼로그 구현
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeErrorDialog.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeScannerActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendDialog.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationActivity.kt
  app/src/main/res/layout/dialog_barcode_error.xml
  app/src/main/res/layout/dialog_recommend.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 영주🐼

#44 #14 [setting] 서버 세팅
  app/src/main/java/com/sopt/peekabookaos/data/entity/BaseResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/CreateUpdateRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/CreateUpdateRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/NotificationRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/NotificationRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/RecommendRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/RecommendRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/SearchRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/CreateUpdateService.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/DetailService.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/NotificationService.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/RecommendService.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/SearchService.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/ShelfService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/CreateUpdateDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/DetailDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/NotificationDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/RecommendDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/SearchDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/ShelfDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitServiceModule.kt
Labels: Pull Request🔥, 영주🐼, setting

#43 #38 [fix] 상세뷰/ 내 책장, 친구 책장 뷰 수정
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
  app/src/main/res/layout/activity_detail.xml
Labels: fix, Pull Request🔥, 하정🐥

#47 #45 [add] bookshelf,pick,notification /clickListenter, Intent 추가
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyActivity.kt
  app/src/main/res/layout/fragment_bookshelf.xml
Labels: add, Pull Request🔥, 강희🐬

#56 #55 [feat] 상세뷰/ 서버구현
  app/src/main/java/com/sopt/peekabookaos/data/entity/Recommend.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/RecommendResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/RecommendRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/RecommendRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/RecommendService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/RecommendDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendViewModel.kt
  app/src/main/res/layout/item_recommend.xml
Labels: feat, Pull Request🔥, 하정🐥

#59 #51 [feat] pick 조회 / 서버 구현
  app/src/main/java/com/sopt/peekabookaos/data/entity/PickModify.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/ShelfService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/ShelfDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
Labels: feat, Pull Request🔥, 강희🐬

#61 #54 [feat] 친구 책장 서버 구현/ 서버구현
  app/src/main/java/com/sopt/peekabookaos/data/entity/SelfIntro.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/FriendShelfResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/ShelfService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/ShelfDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfPickAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
Labels: feat, Pull Request🔥, 강희🐬

#62 #57 [feat] detail뷰/ 서버 구현
  app/src/main/java/com/sopt/peekabookaos/data/entity/Detail.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/Recommend.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/DetailService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/DetailDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/item_recommend.xml
Labels: feat, Pull Request🔥, 하정🐥

#63 #58 [feat] 알림 서버 구현/ 서버구현
  app/src/main/java/com/sopt/peekabookaos/data/entity/Notification.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/NotificationRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/NotificationRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/NotificationService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/NotificationDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationViewModel.kt
  app/src/main/res/layout/item_notification.xml
Labels: feat, Pull Request🔥, 강희🐬

#66 #53 [feat] 사용자 검색 / 팔로우,언팔로우 서버 통신 구현
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/FollowResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/SearchRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/SearchService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/SearchDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/user/SearchUserViewModel.kt
Labels: feat, Pull Request🔥, 영주🐼

#68 #65 [feat] pick수정/ pick수정 서버 연결
  app/src/main/java/com/sopt/peekabookaos/data/entity/request/PickRequest.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/NotificationService.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/ShelfService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/ShelfDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
Labels: feat, Pull Request🔥, 강희🐬

#70 #67 [ui] 다이얼로그 작업
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommedationViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendDialog.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/util/dialog/ConfirmClickListener.kt
  app/src/main/java/com/sopt/peekabookaos/util/dialog/WarningDialogContent.kt
  app/src/main/java/com/sopt/peekabookaos/util/dialog/WarningDialogFragment.kt
  app/src/main/java/com/sopt/peekabookaos/util/dialog/WarningType.kt
  app/src/main/java/com/sopt/peekabookaos/util/extensions/DialogFragmentExt.kt
  app/src/main/java/com/sopt/peekabookaos/util/extensions/FragmentExt.kt
  app/src/main/res/font/montserrat.xml
  app/src/main/res/font/montserrat_bold_f.ttf
  app/src/main/res/layout/activity_create_update_book.xml
  app/src/main/res/layout/activity_recommendation.xml
  app/src/main/res/layout/dialog_warning.xml
  app/src/main/res/layout/item_bookshelf_pick.xml
  app/src/main/res/layout/item_recommend.xml
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, ui, 영주🐼

#72 #69 [fix] Intent 작업
  app/src/main/java/com/sopt/peekabookaos/data/entity/SelfIntro.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfPickAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfShelfAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/res/menu/menu_bookshelf_pop_up.xml
Labels: feat, Pull Request🔥, 강희🐬

#77 #76[fix] bookshelf / databinding > viewbinding 으로 변경
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/res/layout/fragment_bookshelf.xml
Labels: fix, Pull Request🔥, 강희🐬

#75 #74[feat] bookshelf / Intent 수정- LOCATION 넘겨주기, Header 추가
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
Labels: feat, Pull Request🔥, ui, 강희🐬

#78 #64 [feat] 책상세뷰/ delete 서버 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/data/entity/BookComment.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/Detail.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/DetailResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/DetailService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/DetailDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createUpdateBook/CreateUpdateBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendViewModel.kt
  app/src/main/res/layout/activity_detail.xml
Labels: feat, Pull Request🔥, 하정🐥

#80 #79 책 추천하기 뷰/ 서버 구현
  app/build.gradle
  app/src/main/java/com/sopt/peekabookaos/data/entity/request/RecommendationRequest.kt
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/RecommendationResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/RecommendRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/RecommendRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/RecommendService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/RecommendDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommedationViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookViewModel.kt
  app/src/main/res/layout/activity_recommendation.xml
Labels: feat, Pull Request🔥, 하정🐥

#83 #73 [fix] bookshelf.notification,pick design update
  app/src/main/java/com/sopt/peekabookaos/data/entity/PickModify.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfShelfDecoration.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationDecoration.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyDecoration.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
  app/src/main/res/drawable-hdpi/ic_bookshelf_pick.png
  app/src/main/res/drawable-hdpi/shape_white88fill_redline_0_rect_1.xml
  app/src/main/res/drawable-hdpi/shape_white88fill_redline_0_rect_2.xml
  app/src/main/res/drawable-mdpi/ic_bookshelf_pick.png
  app/src/main/res/drawable-xhdpi/ic_bookshelf_pick.png
  app/src/main/res/drawable-xxhdpi/ic_bookshelf_pick.png
  app/src/main/res/drawable-xxxhdpi/ic_bookshelf_pick.png
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/fragment_bookshelf.xml
  app/src/main/res/layout/item_bookshelf_pick.xml
  app/src/main/res/layout/item_bookshelf_shelf.xml
  app/src/main/res/layout/item_bookshelf_user_profile.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/layout/item_pick_modify.xml
  app/src/main/res/values/themes.xml
Labels: fix, Pull Request🔥, ui, 강희🐬

#82 #48 [fix] setOnClickListener를 setOnSingleClickListener로 수정
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/ktlint.xml
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeErrorDialog.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeScannerActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createUpdateBook/CreateUpdateBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/user/SearchUserActivity.kt
  app/src/main/java/com/sopt/peekabookaos/util/dialog/WarningDialogFragment.kt
  app/src/main/java/com/sopt/peekabookaos/util/extensions/ContextExt.kt
Labels: fix, Pull Request🔥, 하정🐥

#88 #84 [feat] 책 검색(텍스트) / 서버구현
  app/src/main/java/com/sopt/peekabookaos/data/entity/response/CreateBookResponse.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/NaverRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/NaverRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/data/service/NaverService.kt
  app/src/main/java/com/sopt/peekabookaos/data/source/remote/NaverDataSource.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createUpdateBook/CreateUpdateBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createUpdateBook/CreateUpdateBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookAdapter.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookViewModel.kt
  app/src/main/res/layout/activity_create_update_book.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_recommendation.xml
  app/src/main/res/layout/item_search_book.xml
Labels: feat, fix, Pull Request🔥, 영주🐼

#90 #87 [fix] 바코드 분기처리 수정
  app/src/main/java/com/sopt/peekabookaos/data/entity/NaverBookItem.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/NaverRepository.kt
  app/src/main/java/com/sopt/peekabookaos/data/repository/NaverRepositoryImpl.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeScannerActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookViewModel.kt
  app/src/main/res/layout/item_recommend.xml
Labels: fix, Pull Request🔥, 영주🐼

#91 #40 [fix] QA 진행
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
  app/src/main/res/layout/fragment_bookshelf.xml
  app/src/main/res/layout/item_notification.xml
Labels: fix, Pull Request🔥, ui, 강희🐬

#92 #86 [fix] 마이페이지 구현
  app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
  app/src/main/res/drawable-xxxhdpi/img.png
  app/src/main/res/drawable/ic_my_page_edit.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: fix, Pull Request🔥, ui, 하정🐥

#96 #95 [fix] 디자인 qa 적용
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfPickDecoration.kt
  app/src/main/res/layout/fragment_bookshelf.xml
  app/src/main/res/layout/item_bookshelf_pick.xml
  app/src/main/res/values/strings.xml
Labels: fix, ui, 강희🐬

#98 #26 [fix] QA 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createUpdateBook/CreateUpdateBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommedationViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommendationActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookViewModel.kt
  app/src/main/res/drawable/shape_g1_line_circle.xml
  app/src/main/res/drawable/shape_white88fill_redline_0_rect_1.xml
  app/src/main/res/drawable/shape_white88fill_redline_0_rect_2.xml
  app/src/main/res/layout/activity_create_update_book.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_recommendation.xml
  app/src/main/res/layout/activity_search_user.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/values/strings.xml
Labels: fix, Pull Request🔥, 영주🐼

#100 #89 [fix] QA수정
  app/src/main/java/com/sopt/peekabookaos/data/entity/BookComment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createUpdateBook/CreateUpdateBookActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/createUpdateBook/CreateUpdateBookViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
  app/src/main/res/layout/activity_detail.xml
Labels: fix, Pull Request🔥, 하정🐥

#99 #97 [fix] QA 수정
  app/src/debug/ic_launcher-playstore.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/debug/res/values/ic_launcher_background.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
  app/src/main/res/drawable/background_splash.xml
  app/src/main/res/values/styles.xml
Labels: fix, Pull Request🔥, 강희🐬

#102 #101 [fix] 로딩뷰 수정, 자잘한 디자인 수정
  app/build.gradle
  app/src/debug/res/values/ic_launcher_background.xml
  app/src/main/AndroidManifest.xml
  app/src/main/assets/splash_lottie.json
  app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
  app/src/main/res/drawable/ic_bottom_bookshelf.xml
  app/src/main/res/drawable/ic_bottom_my_page.xml
  app/src/main/res/drawable/ic_bottom_recommend.xml
  app/src/main/res/layout/activity_search_user.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/menu/menu_bookshelf_pop_up.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: fix, Pull Request🔥, 영주🐼
