Repository team-peekabook/Peekabook-AOS, pull requests merged in 2023-08, with the labels that each got.

#240 #236 [fix] 뒤로가기 연타 로직 추가
  app/src/main/java/com/sopt/peekabookaos/PeekabookApplication.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/networkError/NetworkErrorActivity.kt
Labels: feat, Pull Request🔥, 영주🐼

#247 #246 [fix] 자동로그인 만료 후 기존 Api 무한호출되는 버그 수정
  app/src/main/java/com/sopt/peekabookaos/di/RefreshRetrofitModule.kt
  app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/main/MainViewModel.kt
Labels: fix, Pull Request🔥, 영주🐼

#249 #248 [QA] 책장뷰 디자인 수정
  app/src/main/res/drawable/shape_white66fill_redline_0_rect.xml
  app/src/main/res/layout/fragment_bookshelf.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, 강희🐬, QA

#252 #251 [QA] bookshelf userinput
  app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyBottomSheetFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputBottomSheetFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputViewModel.kt
  app/src/main/res/layout/dialog_profile_bottom_sheet.xml
  app/src/main/res/layout/dialog_user_input_bottom_sheet.xml
  app/src/main/res/layout/item_bookshelf_pick.xml
  app/src/main/res/layout/item_bookshelf_shelf.xml
  app/src/main/res/layout/item_pick_modify.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request🔥, 강희🐬, QA

#253 #250 [QA] userinput 이미지 90도 회전 방지
  app/build.gradle
  app/src/main/java/com/sopt/peekabookaos/util/ContentUriRequestBody.kt
  app/src/main/java/com/sopt/peekabookaos/util/ImageUtil.kt
Labels: Pull Request🔥, 강희🐬, QA

#254 #245 [chore] 프로필수정뷰 previousNickname 변수 캡슐화 및 정보 은닉
  app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
  app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyViewModel.kt
Labels: Pull Request🔥, 하정🐥, QA
